name: Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential \
              python3-pip \
              git \
              autoconf \
              libtool \
              pkg-config \
              zlib1g-dev \
              libncurses-dev \  # Replaces libtinfo5
              cmake \
              libffi-dev \
              libssl-dev \
              ninja-build
          pip install buildozer cython==0.29.19
          
      - name: Build APK
        run: |
          buildozer init
          sed -i "s/pkgname = .*/pkgname = twentyfive/" buildozer.spec
          buildozer -v android debug
